# .github/workflows/build-exe.yml
name: Build EXE

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  release:
    types: [ created ]

jobs:
  build:
    runs-on: windows-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v3
      with:
        python-version: '3.9'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pandas openpyxl tkinter pyinstaller

    - name: Create executable
      run: |
        pyinstaller --onefile --windowed table_splitting.py

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: table-splitting-exe
        path: dist/table_splitting.exe

    - name: Upload release asset
      if: github.event_name == 'release'
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: dist/table_splitting.exe
        asset_name: table_splitting.exe
        asset_content_type: application/octet-stream
